# version: 2.1
# commands: # a reusable command with parameters
#   greeting:
#     parameters:
#       to:
#         default: "world"
#         type: string
#     steps:
#       - run: echo "Hello <<parameters.to>>"
# jobs:
#   my-job:
#     docker:
#       - image: cimg/base:stable
#     steps:
#       - greeting:
#           to: "My-Name"
# workflows:
#   my-workflow:
#     jobs:
#       - my-job

version: 2

jobs:

  build:

    docker:

      # Use a suitable Docker image for your project

      - image: <your-docker-image>

    steps:

      - checkout

      - run: |

          # Install SonarQube scanner

          npm install -g sonar-scanner

          # Run SonarQube analysis

          sonar-scanner \

            -Dsonar.host.url=<SonarQube URL> \

            -Dsonar.login=<SONAR_TOKEN> \

            -Dsonar.projectKey=<Project Key> 


